#If enabled you can't claim on blacklisted worlds.
UseBlacklist: false
BlacklistedWorlds:
- WorldA
- WorldB

#If enabled you can't claim on NON-WHITELISTED worlds.
UseWhitelist: false
WhitelistedWorlds:
- WorldA
- WorldB
