#If enabled you can't build on blacklisted worlds.
UseBlacklist: false
BlacklistedWorlds:
- WorldA
- WorldB

#If enabled you can't build on NON-WHITELISTED worlds.
UseWhitelist: false
WhitelistedWorlds:
- WorldA
- WorldB
