name: TerrainClaim
main: net.zabszk.terrain.Main
description: Adds chunk claiming.
version: 1.1.4
author: zabszk
softdepend: [WorldGuard]

commands:
   terrain:
      description: Main menu.
      usage: /terrain
      aliases: [claim, tr, ch, chunk]